# Generated by Django 5.1.2 on 2024-11-05 08:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hamaca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=100)),
                ('longitud', models.FloatField(default=1.0)),
                ('peso_maximo', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(choices=[('BBVA', 'BBVA'), ('UNI', 'Unicaja'), ('CAI', 'Caixa'), ('ING', 'ING')], max_length=4)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hamacas.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(default=1.0)),
                ('comentario', models.CharField(max_length=200)),
                ('fecha_valoracion', models.DateTimeField(default=django.utils.timezone.now)),
                ('hamaca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hamacas.hamaca')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hamacas.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='voto',
            field=models.ManyToManyField(through='hamacas.Valoracion', to='hamacas.hamaca'),
        ),
    ]
