# Generated by Django 5.1.2 on 2024-11-05 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamacas', '0002_alter_banco_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banco',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hamacas.usuario'),
        ),
    ]
